name: Build Pipeline

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:

jobs:
  build-and-test:
    name: Validate and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code ${{ github.run_id }} ${{ github.run_number }}
        run: echo 'Checkout code'

      - name: Build DEV
        if: github.ref == 'refs/heads/develop'
        run: echo 'Build DEV'

      - name: Upload DEV artifact
        if: github.ref == 'refs/heads/develop'
        run: echo 'Upload DEV'

      - name: Build QA
        if: github.ref == 'refs/heads/develop'
        run: echo 'Build QA'

      - name: Upload QA artifact
        if: github.ref == 'refs/heads/develop'
        run: echo 'Upload QA'

      - name: Build PROD
        if: github.ref == 'refs/heads/master'
        run: echo 'Build PROD'

      - name: Upload PROD artifact
        if: github.ref == 'refs/heads/master'
        run: echo 'Upload PROD'

  deploy-dev:
    name: Deploy to DEV
    if: github.ref == 'refs/heads/develop'
    needs: [build-and-test]
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Download a artifact ${{ github.run_id }} ${{ github.run_number }}
        run: echo 'Download DEV'

      - name: Configure AWS credentials
        run: echo 'Configure DEV'

      - name: Deploy
        run: echo 'Deploy DEV'

  deploy-qa:
    name: Deploy to QA
    if: github.ref == 'refs/heads/develop'
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Download a artifact ${{ github.run_id }} ${{ github.run_number }}
        run: echo 'Download QA'

      - name: Configure AWS credentials
        run: echo 'Configure QA'

      - name: Deploy
        run: echo 'Deploy QA'

  deploy-prod:
    name: Deploy to PROD
    if: github.ref == 'refs/heads/master'
    needs: [build-and-test]
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Download a artifact ${{ github.run_id }} ${{ github.run_number }}
        run: echo 'Download PROD'

      - name: Configure AWS credentials
        run: echo 'Configure PROD'

      - name: Deploy
        run: echo 'Deploy PROD'