name: Pull Request Pipeline

on:
  pull_request:
    branches: [ develop ]

jobs:
  install-and-test:
    name: Install and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code ${{ github.run_id }} ${{ github.run_number }}
        run: echo 'Checkout code'
