name: Manual Pipeline

on:
  workflow_dispatch:
    inputs:

jobs:
  build-and-test:
    name: Validate and Build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code ${{ github.run_id }} : ${{ github.run_number }}
        run: echo 'Checkout code'
